- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/NoltoApplication.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Like.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Step.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/Tech.java
- backend/src/main/java/com/wooteco/nolto/user/application/AuthService.java
- backend/src/main/java/com/wooteco/nolto/user/application/NotFoundException.java
- backend/src/main/java/com/wooteco/nolto/user/domain/AuthenticationPrincipal.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/main/java/com/wooteco/nolto/user/domain/UserRepository.java
- backend/src/main/java/com/wooteco/nolto/user/infrastructure/AuthorizationExtractor.java
- backend/src/main/java/com/wooteco/nolto/user/infrastructure/JwtTokenProvider.java
- backend/src/main/java/com/wooteco/nolto/user/ui/AuthController.java
- backend/src/main/java/com/wooteco/nolto/user/ui/AuthenticationPrincipalArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/TokenRequest.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/TokenResponse.java
- backend/src/main/resources/application.properties
- backend/src/test/java/com/wooteco/nolto/user/domain/UserTest.java
- build.gradle 의존성 추가
- 패키지 구조 세팅 (도메인 중심)
- 로그인 기능 추가
- 로그인 성공 시 토큰 발행
- Resolver 적용
- Closes #8 
- ~~더미 데이터 추가 진행중~~ 👉 추가 완료
- 인터셉터 미적용
- 토큰 자체에 대한 유효성 검증 필요
> feat: 로그인 기능 추가

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/FeedRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Step.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/AuthController.java
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedTest.java
- backend/src/test/java/com/wooteco/nolto/user/domain/UserTest.java
* 작성한 글을 DB에 저장
* Step에 따라 필수 작성 항목을 다르게 처리함
+ Step.COMPLETE 일 시 deployedUrl 은 필수 (null이 될 수 없음)
* FeedRequest, FeedResponse 추가
* DataLoader에 Feed 더미 데이터 추가
Closes #13 
* FeedResponse 에 id 만 추가해둔 상태
* url 정규표현식 검사 추가 필요
* Step과 url을 묶어놓으면 어떨까에 대한 회의 필요
+ 현재는 Feed 주생성자에서 검증을 하고 있음
> feat: 글 작성 기능 추가

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/NotFoundException.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Like.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Step.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedAuthorResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedDetailResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedSimpleResponse.java
- backend/src/main/java/com/wooteco/nolto/tech/ui/dto/TechResponse.java
- backend/src/main/java/com/wooteco/nolto/user/AuthenticationPrincipalConfig.java
- backend/src/main/java/com/wooteco/nolto/user/application/AuthService.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/main/java/com/wooteco/nolto/user/ui/AuthController.java
- backend/src/main/resources/logback-access.xml
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedTest.java
- backend/src/test/java/com/wooteco/nolto/user/domain/UserTest.java
- 단일 피드 조회 기능 추가
- http 요청 로그백 추가
Closes #9 
- Jackson에서 Java Object -> JSON 변환시 getter가 필수
- Feed에 좋아요를 누른 User를 찾는 로직 리팩토링 필요
> feat: 피드 단일 조회 기능 추가

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Filter.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedCardResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedSimpleResponse.java
- 최신 피드를 조회한다. (default = 최신순 피드)
- 최신 피드의 필터링을 추가한다.
- SOS인가?
- Step이 complete인가?
- Step이 progress인가?
Closes #10 
- 현재 최신 피드는 id순으로 가고 있다.
- 추후에 생성 날짜 순으로 수정이 필요
> feat: 최신 피드 조회 기능 구현

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- findAll 시 빈 프로퍼티를 매개변수로 받는 문제 해결
- Closes #52 
- 코딩 조심하자
- 이상한 코드 남기고 커밋하지 말좌
> fix(feed): find-all 시 빈 프로퍼티를 매개변수로 받는 문제 해결

- backend/build.gradle
- backend/src/main/resources/application.properties
- backend/src/main/resources/application.yml
- properties 대신 yml로 환경설정
- dev, test, prod 별로 환경설정 
Closes #54 
- realdb.yml만 git의 관리 안받는 곳에서 생성해주기
> build: profile별 환경 설정 추가

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- backend/src/main/java/com/wooteco/nolto/image/config/ImageConfig.java
- backend/src/main/resources/application.yml
- s3 저장소 연동
- feed 업로드시 이미지 파일 받아서 저장하는 기능 구현
Closes #93 
- s3 라이브러리 사용 관련 테스트 구현 고려해보기 
- 프론트한테 기능을 주기 위해 빠르게 배포해보는 단계이므로 검증이 필요함
> feat(image): S3 저장소로 이미지 업로드 기능 구현 

- backend/src/main/java/com/wooteco/nolto/BaseEntity.java
- backend/src/main/java/com/wooteco/nolto/NoltoApplication.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/test/java/com/wooteco/nolto/BaseEntityTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedRepositoryTest.java
- 생성/수정 날짜 추가 및 테스트 코드 작성
- 피드 조회 시 생성, 수정 날짜 순으로 정렬 및 테스트 코드 추가
- Close #25 
- 생성 날짜를 테스트 하는 부분에서 기존의 id 순으로 테스트 하던 것과 결국 똑같음 ㅠㅠ 
- 확실한 통합 테스트를 위해서는 setId()나 setCreatedDate()가 필요한데 다 private으로 막혀있어오,,,
- 근데 CreatedDate()나 UpdatedDate()가 정상적으로 들어가는 테스트는 구현 되어 있어서 일단 풀리퀘 날립니다 👍
> feat:  글쓰기에 생성/수정 날짜 및 시간 추가

- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedResponse.java
- backend/src/test/java/com/wooteco/nolto/api/FeedControllerTest.java
- 글이 수정되지 않으면 수정 날짜가 존재하지 않는데 이를 필수값으로 주기에 에러 발생
- 피드 상세 조회시 수정 날짜 제거
- 글쎼유
> fix(): 단일 조회에서 수정 날짜 제거

- frontend/src/commonStyles.ts
- frontend/src/components/@common/Avatar/Avatar.styles.ts
- frontend/src/components/StretchCard/StretchCard.styles.ts
- frontend/src/components/StretchCard/StretchCard.tsx
- frontend/src/pages/Home/Home.tsx
refactor: StretchCard의 크기 작게 조정
(이렇게 보면 티는 안 남)
진행중, 조립중 태그 크기는 @0307kwon 미키가 수정 예정
> [FE] refactor: StretchCard의 크기 작게 조정

- frontend/custom.d.ts
- frontend/src/assets/arrowUp.svg
- frontend/src/components/@common/ErrorMessage/ErrorMessage.stories.tsx
- frontend/src/components/@common/ErrorMessage/ErrorMessage.styles.ts
- frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
- frontend/src/components/@common/FileInput/FileInput.styles.ts
- frontend/src/components/@common/Toggle/Toggle.styles.ts
- frontend/src/components/TechInput/TechInput.styles.ts
- frontend/src/constants/api.ts
- frontend/src/constants/message.ts
- frontend/src/pages/Upload/Upload.styles.ts
- frontend/src/pages/Upload/Upload.tsx
작업하다가 뒤늦게 브랜치를 나누지 않았다는 사실을 알았습니다ㅠ
뒤늦게 깨닫고 나누려고 했지만 너무 관계가 밀접해서 나누지 못했습니다
PR이 너무 커진점... 반성하겠습니다 😭
추가된 대략적인 기능들
- validation
- redirection
- svg에 fill 속성으로 색을 변경할 수 있도록 수정
- UploadFeed 타이핑도 다시 살짝 수정하였습니다.
Closes #144 
이쁨
근데 문제점이 2가지 있습니다.
1. text area에 개행을 넣으면 게시물 등록이 안됩니다.
2. 대표 이미지는 옵셔널 아니었나용? 지금 대표 이미지가 없으면 등록이 안됩니다.
> [FE] Upload 페이지 최소 구현 기능 완료

- frontend/package.json
- frontend/src/assets/carouselArrow.svg
- frontend/src/components/LevelLinkButton/LevelLinkButton.styles.ts
- frontend/src/components/RegularCard/RegularCard.styles.ts
- frontend/src/hooks/@common/useOnScreen.ts
- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Home/Home.tsx
- frontend/webpack.config.js
- frontend/yarn.lock
- babel-plugin-styled-components 설치
- 브라우저 개발자도구에서 컴포넌트 이름 확인용
- fix: `RegularCard` 글씨 정렬 왼쪽으로 배치 
Closes #138
- carousel 코드 이해 못함 (출처: <https://codepen.io/onion2k/pen/xxZYBVj>)
- `RegularCard` 컨텐츠 글씨 정렬 서버에서는 잘 되나 스토리북에서는 또 약간 틀어짐
> [FE] feat: Home의 Hot Toys 보여줄 개수 설정, carousel 구현

- frontend/src/components/@common/ErrorMessage/ErrorMessage.styles.ts
- ErrorMessage 폰트 크기 0.75rem으로 수정
- 말풍선 arrow 위치 수정 => **맥에서 확인해주세요!!**
Closes #155
> [FE] fix: ErrorMesage 폰트 크기, 레이아웃 수정

- frontend/src/components/@common/ErrorMessage/ErrorMessage.styles.ts
- frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
mac에서 ErrorMessage 스타일링 깨지는 버그 수정
Closes #167
- 구조 많이 바꿈
- height 좀 더 줄여도 될 것 같아서 (원래 상태의 input과 error box의 크기가 비슷해서 중요도가 같아 보임) 조금 줄임
> [FE] fix: mac에서 ErrorMessage 스타일링 깨지는 버그 수정

- frontend/.storybook/preview-body.html
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/context/modal/ModalProvider.styles.ts
- frontend/src/context/notification/NotificationProvider.stories.tsx
- frontend/src/context/notification/NotificationProvider.styles.ts
- frontend/src/context/notification/NotificationProvider.tsx
- frontend/src/context/notification/useNotification.ts
- frontend/src/context/snackBar/SnackBarProvider.stories.tsx
- frontend/src/context/snackBar/SnackBarProvider.styles.ts
- frontend/src/context/snackBar/useSnackBar.ts
- frontend/src/context/techTag/input/TechInput.tsx
- frontend/src/types.ts
- z-index 관계 조정 (modal, snackbar)
- Provider hooks -> export default 로 통일
Closes #220
스토리북이 안 돌아감
`Target container is not a DOM element.`
에러 발생
> [FE] feat: Notification (Provider) 컴포넌트 구현

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- feed 등록 : 이미지가 없으면 디폴트 이미지로 설정
- feed 수정 : 이미지가 없으면 변경이 이루어지지 않도록 수정
기존의 피드 등록 시 MultipartFile이 empty인 경우에만 디폴트 이미지를 설정해주고 있는데용
프론트에서 피드 요청 값 중 이미지 자체를 안 보내게 될 경우 null이 되기 때문에 이 부분에 대한 검증 로직을 추가해 디폴트 이미지로 설정해주었습니다.
> feed 업로드 시 이미지가 없으면 수정을 안하도록 수정

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- 검색 기능에서 필터링을 포함하여 검색할 수 있도록 보강
- 프로덕션 코드 다음과 같이 보강
- FeedController
```java
@GetMapping("/search")
public ResponseEntity<List<FeedCardResponse>> searchResponse(@RequestParam(required = false, defaultValue = "") String query,
@RequestParam(required = false, defaultValue = "") String techs,
@RequestParam(required = false, defaultValue = "all") String filter) {
List<FeedCardResponse> feeds = feedService.search(query, techs, filter);
return ResponseEntity.ok(feeds);
}
```
- FeedService
```java
public List<FeedCardResponse> search(String query, String techs, String filter) {
SearchStrategy searchStrategy = SearchStrategyFactory.of(query, techs).findStrategy();
Set<Feed> searchFeed = searchStrategy.search(query, techs);
Feeds feeds = new Feeds(new ArrayList<>(searchFeed));
FilterStrategy …
```
> feat: 검색 기능에 필터링 기능 추가

- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
<springProfile name="file-error-logging">
<appender-ref ref="INFO_FILE_POLICY"/>
<appender-ref ref="ERROR_FILE_POLICY"/>
</springProfile>
위와같이 file-error-logging 안에는 INFO_FILE_POLICY 참조가 없어서 발생하는 에러였음
이것을 지우고 application.yml 에 file-error-logging,file-info-logging 둘다 성정하도록 변경
Closes #250
> fix(logging): logback-spring.xml 오류나는 설정 수정 및 그에 맞게 application.yml 수정

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- frontend/package.json
> fix: 피드 수정 시 태그 추가 버그 

- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/acceptance/UserAcceptanceTest.java
- `GET: /members/me` 에 대한 인수테스트를 작성했습니다. 
- 토큰이 있는 경우, `MemberResponse`가 정상 반환됩니다.
- 토큰이 없는 경우, `ExceptionResponse`가 반환됩니다. 
- 기존의 `AcceptanceTest`에서 `엄청난_유저`를 public 인스턴스 변수로 분리했습니다. 
- 정상 반환 받은 `MemberResponse`의 내용이 `엄청난_유저`의 내용과 동일함을 판단하기 위함
> test: User 인수 테스트 작성

- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/acceptance/TechAcceptanceTest.java
- auto_complete 파라미터로 기술 태그의 자동 완성 기능을 사용할 수 있다.
- auto_complete 파라미터로 존재하지 않는 기술 태그를 조회해서 응답한다.
- names 파라미터로 이름과 정확히 일치하는 기술 태그들을 조회해서 응답한다.
- names 파라미터로 기술이름과 정확하게 일치하지 않으면 기술 태그를 응답하지 않는다.
- names 파라미터로 기술이름 양 옆에 공백이 있어도 기술 이름만 일치하면 응답해준다.
- names 파라미터에 중복된 기술이름 있으면 중복을 제외하고 반환한다.
Closes #286
> test(Tech): Tech 인수 테스트 작성

- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/acceptance/FeedAcceptanceTest.java
- feed 조회 인수테스트를 위해 feed 더미데이터가 존재해야했기에, 작성자에 대한 유저가 필요했음
- 인기순 인수테스트를 위해 좋아요를 눌러놓을 여러명의 유저도 필요했음
- `가입된_유저의_토큰을_받는다()`를 User를 받아 여러명의 토큰을 만들 수 있는 메서드로 변경
- 임시방편으로 회원 등록 메서드를 추가해놓았는데, 아마 머지 시 이 메서드의 구조와 위치가 다시 논의되지 않을까함
- 머지가 되면 `피드_업로드되어_있음()`이 피드 업로드 인수테스트 메서드로 바뀔 것 같음
- `피드에_좋아요_눌러져있음()`을 좋아요 눌러져있는 피드를 위해 요청만 보내는 RestAssured 코드 작성
- 이도 머지가 되면 인수테스트용 메서드로 바뀌지 않을까
Closes #276 
- 피드 업로드, 좋아요에 대해 임시 방편 RestAssured 메서드를 머지시 교체할 듯 함
- 인기순 피드에 좋아요를 눌러놓을라고 likeService를 가져다 썼는데, 이 like에 대한 insert 쿼리가 안나감 
- 아래의 코드를 참고...
- 왜지왜지왜지??????????????
```java
@DisplayName("인기순으로 피드를 조회한다.")
@Test
void hotResponse() {
// given
likeService.addLike(좋아요_1개_누를_유저, 진행중_좋아요3개_1번째_피드_ID);
likeService.addLike(좋아요_2개_누를_유저, 진행중_좋아요3개_1번째_피드_ID);
likeService.addLike(좋아요_3개_누를_유저, 진행중_좋아요3개_1번째_피드_ID); …
```
> feat(): 토큰이 필요하지 않는 feed 관련 인수테스트 구현

- backend/src/main/resources/application.yml
- refactor: 이미지 관련 요청 10MB 까지 허용하도록 수정
- nginx 웹 서버와 요청 사이즈 동일하게 하기 위함
> refactor: 이미지 관련 요청 10MB 까지 허용하도록 수정

- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/dto/GithubUserResponse.java
- github: name이 없는 사용자가 있어 login으로 변경
Closes #283
> fix(GithubUserResponse): 깃허브 가입 시 닉네임이 없으면 생기는 버그 수정

- frontend/src/components/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/components/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/components/RegularCard/RegularCard.styles.ts
- frontend/src/components/StretchCard/StretchCard.styles.ts
- recent feed card 크기 키우기
- 피드 상세 페이지 사진 비율 조정
- hot feeds hover 시 레이아웃 깨지는 문제 수정
> [FE] 피드 컨텐츠 관련 CSS 수정

- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Home/Home.tsx
Home의 trends 태그 hover 시 bar에도 underline이 생기는 버그 수정
Closes #307
> [FE] fix: Home의 trends 태그 underline 버그 수정

- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/constants/message.ts
- frontend/src/context/techTag/chip/TechChips.tsx
- frontend/src/pages/Modify/Modify.tsx
- frontend/src/pages/Upload/Upload.tsx
- TechChip type button으로 변경
- 피드 수정 페이지에서 '등록' 버튼을 '수정' 버튼으로 변경
- 피드 등록/수정 시 noti가 아닌 snackbar 띄우기
- 피드 수정 완료 시 해당 피드 상세 페이지로 리다이렉트
> [FE] refactor: 피드 수정 페이지 디테일 변경

- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- ControllerAdvice 에서 StackTrace 를 여러줄의 에러 로그로 출력하던 부분 수정
+ StringBuilder 를 사용해서 하나의 문자열로 만들어서 출력함
```java
StringBuilder sb = new StringBuilder();
for (String splitMessage : spiltMessages) {
log.warn(splitMessage);
sb.append(splitMessage).append("\n");
}
log.error(sb.toString());
```
Closes #316 
슬랙 메세지 300개 무서워요
> refactor(logging): 에러 로그의 StackTrace를 하나의 출력으로 찍도록 수정

- frontend/src/components/RecentFeedsContent/RecentFeedsContent.styles.ts
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/components/SearchResultContent/SearchResultContent.styles.ts
- frontend/src/components/SearchResultContent/SearchResultContent.tsx
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/RecentFeeds/RecentFeeds.styles.ts
- frontend/src/pages/SearchResult/SearchResult.styles.ts
최신 피드 & 검색 결과 페이지에서 피드가 넘칠 때 arrow 버튼 추가
너무 썰렁해서 스크롤을 할 수 있음을 표시하기 위해 추가해주었습니다
버튼 눌렀을 때 아직 아무 동작도 하지 않음. 이후 infinite scroll 등 구현 시 추가 예정
> [FE] refactor: 최신 피드 & 검색 결과 페이지에서 피드가 넘칠 때 arrow 버튼 추가

- frontend/src/components/SearchOption/SearchOption.styles.ts
- frontend/src/components/SearchOption/SearchOption.tsx
refactor: 검색옵션 열릴 때 부드러운 효과
`height: auto`면 transition이 동작하지 않음.
임의로 보기 좋은 px 단위로 height를 넣어서 transition을 만들었습니다
> [FE] refactor: 검색옵션 열릴 때 부드러운 효과

- backend/src/docs/asciidoc/member.adoc
- backend/src/main/java/com/wooteco/nolto/user/application/UserService.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/main/java/com/wooteco/nolto/user/ui/UserController.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/CommentHistoryResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/FeedHistoryResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/MemberHistoryResponse.java
- backend/src/test/java/com/wooteco/nolto/acceptance/UserAcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/api/FeedControllerTest.java
- backend/src/test/java/com/wooteco/nolto/api/UserControllerTest.java
- backend/src/test/java/com/wooteco/nolto/user/application/UserServiceTest.java
- **유저 히스토리(좋아요 한 글, 내가 작성한 글, 내가 남긴 댓글)를 조회하는 기능을 구현했어요**
- ArgumentResolver에서 받은 User를 바로 Dto에 넘겨 처리할 수 있지만, 서비스단에서 로직을 구현했어요
- 사실 그냥 Dto에서 정보만 추출해서 포장하면 처리할 수 있는 로직인 것은 맞아요
- 하지만 히스토리 관련 정보들에 조건들이 걸리게 된다면(최근에 올린순으로 정렬 등) 서비스 레이어에서 코드를 수정하게 될 것이라 생각했어요
- 추후 확장성 + 엔티티를 서비스에서 다루는 게 맞지 않나 라는 생각에 서비스레이어에서 처리했습니다
- 아직 댓글 기능이 완전히 구현되지는 않아서 컨트롤러 테스트에서 모킹을 조금 더 쉽게 하고자함도 있었어요
- **컨트롤러/서비스 레이어에 대한 테스트 코드를 작성했어요**
- [컨트롤러]
- UserService를 모킹하여 정해진 MemberHistoryResponse를 반환하게 하였어요
- member.adoc에 해당 스니펫 추가하여 문서화 진행했어요
- [서비스]
- User가 Cascade-All 임을 활용하여 테스트코드를 작성하였어요
- User에 피드/댓글/좋아요 넣고 저장하면 피드/댓글/좋아요가 알아서 저장되어요
- [인수테스트]
- 아직 댓글을 작성하는 엔드포인트가 작성되지 않아 테스트 하기 힘들것이라 판별했어요
- 추후 작성 예정입니다
Closes #342
- 인수테스트에서 API에 대한 요청은 static으로 빼서 다른 인수테스트에서도 활용가능하게 하도록 리팩토링이 필요해 보여요. 
- 제가 하려고 했는데 AcceptanceTest의 …
> feat: 유저 히스토리 조회 기능 구현

- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- develop pull 받아서 돌려봤는데 제 컴퓨터에서 터지는 테스트가 하나 있었습니다. 
- 보니까 젠킨스에서도 같은 테스트가 터져서 저번에 빌드가 실패했더라고요
- entityManager.clear() 한 줄 제거하니까 테스트 코드 잘 돌아서 우선 PR 보냅니다
> fix: 대댓글을 조회한다. 최신 순으로 대댓글이 나열 (아마찌 -> 포모 -> 조엘) 테스트 깨지는 것 수정

- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- fix: "대댓글을 조회한다" 테스트 수정 …
- DB에 저장되는 시간이 너무 비슷하여 제어가 불가능
- Thread.sleep()을 통해 해결
- fix(FeedServiceTest): 저장 시간 제어가 불가능한 테스트 수정 …
- DB에 저장되는 시간이 너무 비슷하여 제어가 불가능
- Thread.sleep()을 통해 해결
- feat(ControllerAdvice): BindException에 대한 ExceptionHandler 구현 …
- ModelAttribute는 MethodArgumentNotValidException으로 핸들링 할 수 없음
- 우다다다 저장할땐 Thread.sleep()을 줘보는 건 어떨까?
> fix: 시간 관련 테스트 수정

- backend/src/docs/asciidoc/tech.adoc
- backend/src/main/java/com/wooteco/nolto/NoltoApplication.java
- backend/src/main/java/com/wooteco/nolto/exception/ErrorType.java
- backend/src/main/java/com/wooteco/nolto/feed/application/CommentService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/LikeService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationEvent.java
- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationEventHandler.java
- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationService.java
- backend/src/main/java/com/wooteco/nolto/notification/domain/Notification.java
- backend/src/main/java/com/wooteco/nolto/notification/domain/NotificationRepository.java
- backend/src/main/java/com/wooteco/nolto/notification/domain/NotificationType.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/Tech.java
- backend/src/main/java/com/wooteco/nolto/user/application/MemberService.java
- backend/src/main/java/com/wooteco/nolto/user/ui/MemberController.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/FeedNotificationResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/MemberResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/NotificationResponse.java
- backend/src/main/java/com/wooteco/nolto/user/ui/dto/ProfileResponse.java
- backend/src/main/resources/db/migration/V6__add_notification.sql
- backend/src/test/java/com/wooteco/nolto/api/MemberControllerTest.java
- backend/src/test/java/com/wooteco/nolto/api/TechControllerTest.java
-  Notification 이벤트 리스너 구현
- Entity, Repository 구현
- 이벤트 객체 구현
- 이벤트 핸들러 구현
- Async와 TransactionEventListener를 통해 NotificationEventHandler 구현
- 하나의 쓰레드는 하나의 트랜잭션만을 가지지 않을까하여 작성
- 최신 기술 조회 테스트 코드 작성
- 댓글 등록/수정 시 알림 기능 구현
- 알림 조회 기능 구현
- 알림 단일 삭제/일괄 삭제 구현
- 알림 조회 시 최신순 정렬
- 로그인 유저의 알림 필드 추가
- notification 테이블 추가한 sql문 추가
Closes #테크API명세 and #댓글알림기능
- 나도 여자 배구 보고 싶어
> feat: 알림 기능 구현

- frontend/src/components/ErrorFallback/ErrorFallback.styles.ts
error 글씨가 왼쪽으로 쏠려 있었음
-> 중앙 정렬 맞춤!
> [FE] fix: errorfallback의 메시지 중앙 정렬 수정

- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/CommentLike.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
엄청난 연관관계와의 싸움..
- 댓글 삭제 시 대댓글이 자동으로 지워지기 위해 해야하는 관계 끊기 작업
- 댓글을 작성한 유저와의 관계
- 댓글이 속한 피드와의 관계
- 댓글에 있는 모든 좋아요와의 관계
- 댓글에 속한 대댓글들 또한 위의 관계를 모두 끊어줘야함
Closes #385 
앞으로 연관관계와의 전쟁을 해야할지도..
> refactor(comment): 댓글 삭제시 모든 연관관계를 끊어주도록 수정

- frontend/src/__mocks__/fixture/User.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/components/UserProfile/UserProfile.styles.ts
- frontend/src/components/UserProfile/UserProfile.tsx
- frontend/src/constants/common.ts
- frontend/src/constants/message.ts
- frontend/src/context/dialog/DialogProvider.styles.ts
- frontend/src/context/dialog/DialogProvider.tsx
- frontend/src/hooks/queries/profile/useNicknameCheck.ts
- frontend/src/hooks/queries/profile/useNotiDelete.ts
- frontend/src/hooks/queries/profile/useNotiLoad.ts
- frontend/src/hooks/queries/profile/useProfileEdit.ts
- frontend/src/hooks/queries/profile/useProfileLoad.ts
- frontend/src/hooks/queries/useMember.tsx
- frontend/src/hooks/queries/userHistory/useUserHistory.ts
- frontend/src/pages/Mypage/History/History.styles.ts
- frontend/src/pages/Mypage/History/History.tsx
- frontend/src/pages/Mypage/Intro/Intro.styles.ts
- frontend/src/pages/Mypage/Intro/Intro.tsx
- frontend/src/pages/Mypage/Mypage.tsx
- frontend/src/pages/Mypage/Notification/Notification.styles.ts
- frontend/src/pages/Mypage/Notification/Notification.tsx
- frontend/src/types.ts
Mypage의 Intro, History api 연동
Closes #358
Closes #359
Closes #378
(8/8 추가) Closes #388
(8/8 추가) Closes #389 
(8/8 추가)
- `History`에서 메뉴 간 이동 시 한번에 제대로 되지 않는 이슈 있음
- `History`에서 스크롤바를 만들어주고 싶었으나 좌우 탭 이동시 스크롤바가 꼬이는 문제가 있어 일단 보류
- `UserInfo` 타입에서 `socialType`을 빼고 `notifications`를 넣어줌 (서버 api와 통일) 
- dialog에 padding 값 부여
> [FE] Mypage의 Intro, Notification, History api 연동

- backend/src/main/java/com/wooteco/nolto/user/application/MemberService.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
- 프로필 수정시 기존 닉네임과 동일한지 확인하는 로직 추가
- 관련된 테스트 시나리오 추가
Closes #392
> fix(): 기존 닉네임과 동일한 경우 예외를 발생시키던 버그 수정

- backend/src/main/java/com/wooteco/nolto/feed/application/CommentService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/CommentRepository.java
- backend/src/test/java/com/wooteco/nolto/acceptance/CommentAcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceFixture.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- 댓글 좋아요순 -> 최신순으로 변경
- 기존의 좋아요순 댓글 조회 메서드 네이밍 변경 `findAllByFeedIdOrderByLike
> fix: 댓글 좋아요순 -> 최신순으로 변경

- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceFixture.java
- 댓글 저장 시 createdAt이 완전히 똑같아 테스트가 안되는 경우 방지
- fix: fixture thread sleep 추가
- 바쁘다 바뻐
> fix: fixture thread sleep 추가

- frontend/src/components/CommentModule/@common/Comment/Comment.styles.ts
- frontend/src/components/FeedDropdown/FeedDropdown.tsx
- frontend/src/components/UserProfile/UserProfile.tsx
- frontend/src/pages/Mypage/Notification/Notification.tsx
- 댓글 좋아요 정렬
- 피드 삭제 시 snackbar
- 헤더의 유저 프로필 이름 줄바꿈
- Mypage 노티 삭제 시 피드로 이동하는 문제 수정
> [FE] fix: QA 핫픽스

- backend/src/test/java/com/wooteco/nolto/notification/application/NotificationServiceTest.java
- `@Async`가 없어졌으니 혼란을 틈타 트랜잭션 테스트 코드 PR 보내버리기~
-  배겐 컨펌 받고 싶어여(아니다 싶으면 PR 기냥 클로즈 해도 되구여)
- 잘 부탁드립니다 선생님덜
- 컨펌 받을 때 구구절절 설명해드릴 자신 있습니다!!!!!!!!!
- 테스트 여러번 돌려서 확인했슴당
<image src='https://user-images.githubusercontent.com/34594339/128737506-808cbb5f-7a56-4861-92f6-74d80cc53e69.png' width='60%'>
> test: 트랜잭션 시점에 대한 이벤트 리스너 테스트 코드 구현

- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationEvent.java
- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationService.java
- backend/src/test/java/com/wooteco/nolto/acceptance/UserAcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/notification/application/NotificationEventTest.java
- 본인의 피드 좋아요, 댓글 등록, 대댓글 등록에 대한 알림은 발행하지 않도록 변경
- 인수테스트에서 자신의 피드를 좋아요 하고 알림 조회하는 경우 카운트가 올라가지 않도록 변경
- Closes #425
> refactor: 알림에 대한 본인 검증 로직 구현

- backend/src/main/java/com/wooteco/nolto/feed/application/CommentService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/CommentRepository.java
- backend/src/test/java/com/wooteco/nolto/acceptance/CommentAcceptanceTest.java
대댓글 조회 시 JPQL 추가
```java
@Query(value = "select com " +
"from Comment as com " +
"join fetch com.author " +
"join fetch com.feed " +
"where com.feed.id = :feedId and com.parentComment.id = :parentCommentId " +
"order by com.createdDate desc")
List<Comment> findAllByFeedIdAndParentCommentIdWithFetchJoin(@Param("feedId") Long feedId, @Param("parentCommentId") Long parentCommentId);
```
Closes #428
> fix(reply): 대댓글 작성자와 피드 작성자가 일치할 때 isFeedAuthor 가 false 로 응답하는 버그 수정

- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
- fix(MemberServiceTest): 생성 시 User/Feed/Comment/Like 연관관계 제거
- 네이밍이 잘못되어 있어서 수정했습니다
- 이제 진짜 제발 안터질거에요,,, 😅
> fix(MemberServiceTest): 생성 시 User/Feed/Comment/Like 연관관계 제거

- frontend/src/components/@common/Avatar/Avatar.tsx
- frontend/src/components/FeedUploadForm/FeedUploadForm.styles.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/SearchBar/SearchBar.tsx
- frontend/src/components/TrendTechs/TrendTechs.styles.ts
- frontend/src/components/UserProfile/UserProfile.styles.ts
- frontend/src/hooks/queries/profile/useNicknameCheck.ts
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/Mypage/History/History.styles.ts
- frontend/src/pages/Mypage/History/History.tsx
- frontend/src/pages/Mypage/Intro/Intro.styles.ts
- frontend/src/pages/Mypage/Intro/Intro.tsx
- frontend/src/pages/Mypage/Notification/Notification.styles.ts
- frontend/src/pages/Mypage/Notification/Notification.tsx
- frontend/src/pages/Upload/Upload.tsx
- frontend/src/types.ts
- frontend/src/utils/common.ts
> [FE] 2차 UT 이것저것 수정

- backend/src/main/java/com/wooteco/nolto/TomcatWebCustomConfig.java
- 톰캣 버전으로 인한 특수문자 허용 이슈
Closes #475 
- https://dev-jwblog.tistory.com/49
> fix(): 톰캣 문제로 인한 특수 문자 쿼리 허용

- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feeds.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Step.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedCardPaginationResponse.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- 요청 양식
`GET: /feeds/recent2?step=progress&help=true&nextFeedId=2&countPerPage=5`
- 모든 파라미터는 생략 가능
- countPerPage 생략 시 기본으로 15개로 지정
- 응답 양식
```
{
"feeds": [
{
"author": {
"id": 1,
"nickname": "미키",
"imageUrl": "https://dksykemwl00pf.cloudfront.net/amazzi.jpeg"
},
"id": 2,
"title": "title2",
"content": "content2",
"step": "COMPLETE",
"sos": false,
"thumbnailUrl": "https://dksykemwl00pf.cloudfront.net/KakaoTalk_Photo_2021-07-19-14-25-01.png"
},
{
"author": {
"id": 1,
"nickname": "미키",
"imageUrl": "https://dksykemwl00pf.cloudfront.net/amazzi.jpeg"
},
"id": 1,
"title": "title1",
"content": "content1",
"step": "PROGRESS",
"sos": true,
"thumbnailUrl": "https://dksykemwl00pf.cloudfront.net/KakaoTalk_Photo_2021-07-19-14-25-01.png"
}
],
"nextFeedId": null
}
```
- RequestParam의 유효성을 검증하기 위해서 …
> feat: 페이지네이션 구현

- frontend/src/components/@common/ToggleList/ToggleList.styles.ts
- frontend/src/components/CommentModule/@common/CommentForm/CommentForm.tsx
- frontend/src/components/CroppedEllipse/CroppedEllipse.styles.ts
- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/Header/Header.tsx
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.styles.ts
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/components/RegularFeedCard/RegularFeedCard.styles.ts
- frontend/src/components/TrendTechs/TrendTechs.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Home/HomeFeedsContent/HomeFeedsContent.styles.ts
- frontend/src/pages/Mypage/Notification/Notification.styles.ts
- frontend/src/pages/Mypage/Notification/Notification.tsx
- Searchbar 크기 줄임
- 댓글 전송 아이콘, 알림 더보기 아이콘 크기 설정
- Hot Toys와 헤더 사이 간격 넓히기
- Home의 '완성된 프로젝트' 소제목과 피드들 왼쪽 정렬 다름
- 피드 상세 페이지의 기술 스택 정렬 수정
- RegularFeedCard 사진과 글자 간격 조정
- 헤더 넘 쫍은거 간격들 넓힙
- 최신 피드 목록 중앙정렬 (이게 더 나아 보여서...)
---
---
---
- TrendTech overflow 어떻게 하지요?
> [FE] 스타일링 세세한 부분 수정

- backend/src/main/resources/application.yml
``` yaml
server:
compression:
enabled: true
mime-types: text/html,text/plain,text/css,application/javascript,application/json
```
Closes #519
- 응답 Content의 용량이 320byte 일때 압축시 370byte로 늘어남 압축 최소 용량 조건을 500으로 할 수 있는 방법을 찾자
> feat(application.yml): gzip을 위한 설정 추가

- frontend/src/pages/SearchResult/SearchResult.styles.ts
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.styles.ts
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.tsx
fix: 검색 결과 페이지 카드 렌더링 수정
Closes #524
기술스택으로 검색 시
제목/내용으로 검색 시
금방 고치긴 했는데 최신 피드의 인피니트 스크롤 반영되면 얘도 같이 적용해서 머지해야 할 듯!!
> [FE] fix: 검색 결과 페이지 카드 렌더링 수정

- backend/src/main/resources/application.yml
- ec2 서버에 맞는 ffmpeg 관련 경로 yml 설정 추가 
- 알아서 로컬 ffmpeg 패스 맞추세요~
- usr/bin
> fix(): ffmpeg 경로를 ubuntu에 맞추어 설정

- backend/src/main/java/com/wooteco/nolto/WebConfig.java
- resource 차단으로 죽어버린 api 문서 살리기
> fix(): api 문서 resource 경로 허용

- frontend/custom.d.ts
- frontend/src/App.tsx
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.test.tsx
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
피드 상세 페이지에 들어갈 때마다 `Kakao.init`을 계속 해주고 있어서, 이미 `init`되어 있는 경우 중복 `init` 에러가 남
`init`되지 않은 경우에만 `init`하도록 수정
> [FE] fix: 카카오 중복 init 오류 수정

- backend/src/main/java/com/wooteco/nolto/image/application/ImageResizeService.java
* 이미지 변환 작업에서 배경이 투명인 이미지를 올리면 검은색으로 바뀌던 현상 확인
* ImageType 투명도를 지원하도록 변경
* TYPE_INT_RGB -> TYPE_INT_ARGB
Closes #565 
미키의 당당한 자세 주의
> refactor: image 변환시 투명 배경을 유지할 수 있도록 ImageType 변경

- frontend/package.json
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/components/LargeFeedCard/LargeFeedCard.tsx
- frontend/src/components/RegularFeedCard/RegularFeedCard.tsx
- frontend/src/constants/message.ts
- frontend/src/contexts/dialog/DialogProvider.styles.ts
- frontend/src/hooks/queries/useMember.tsx
- frontend/src/pages/Mypage/History/History.tsx
- frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.styles.ts
- frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.tsx
- frontend/src/utils/common.ts
- frontend/yarn.lock
- 검색 결과 페이지 검색 아이콘 표시
- 피드 전체보기 시 마크다운 제거
- 피드 업로드 시 마크다운 영역 에러 메시지 배치 수정
- dialog 팝업창 텍스트 개행
이런 이미지가
이렇게
검색 아이콘도 다시 살리기
이랬던거
이렇게
이랬던거
이렇게 두줄로
> [FE] 검색 결과 페이지 검색 아이콘 표시, 피드 전체보기 시 마크다운 제거

- backend/src/main/java/com/wooteco/nolto/image/application/ImageResizeService.java
if (FileExtension.PNG.equals(FilenameUtils.getExtension(fileName))) {
-> if ("png".equals(FilenameUtils.getExtension(fileName))) {
FilenameUtils.getExtension(fileName)는 ".png" 형식이 아니라 "png" 형식임
> fix: 이미지 배경 투명이 적용 안되는 버그 수정

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/exception/ErrorType.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageConvertService.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageResizeService.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- backend/src/main/java/com/wooteco/nolto/image/config/FFmpegConfig.java
- backend/src/main/java/com/wooteco/nolto/image/infrastructure/FFmpegConverter.java
- backend/src/main/java/com/wooteco/nolto/image/infrastructure/ImageSize.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/wooteco/nolto/image/application/ImageConvertServiceTest.java
- backend/src/test/java/com/wooteco/nolto/image/application/adapter/ImageHandlerAdapterTest.java
- backend/src/test/java/com/wooteco/nolto/image/infrastructure/FFmpegConverterTest.java
* FFmpeg를 애플리케이션이 jar로 관리하도록 수정
- 이를 위한 의존성 추가
- org.bytedeco.javacpp : JNI 코드를 생성하고 C++ 컴파일러에게 전달하여 네이티브 라이브러리를 빌드합니다.
- org.bytedeco.ffmpeg : 실행할 수 있는 ffmpeg를 추출할 수 있습니다.
- org.bytedeco.javacv-platform : OpenCV, FFmpeg 등의 자주 사용하는 라이브러리들을 다양한 플랫폼(운영체제)에 적절한 jar를 제공합니다.
* application.yml에 FFmpeg에 관한 설정 삭제
* 테스트 수정
~~정상인의 수면패턴에 들어가기위해 자세한 내용은 일어나서 정리할게요 🙇~~
[[Java] FFmpeg로 gif파일 mp4로 변환하기 - 2](https://parkadd.tistory.com/126)
Closes #589 
FFmpeg path 설정은 처리했으니 안심하고 테스트 돌리라구
> [BE] refactor: FFmpeg Path 설정 애플리케이션이 관리하도록 수정

- backend/build.gradle
- backend/src/docs/asciidoc/auth.adoc
- backend/src/main/java/com/wooteco/nolto/auth/application/AuthService.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/JwtTokenProvider.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/RedisUtil.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/OAuthController.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/RefreshTokenRequest.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/RefreshTokenResponse.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/TokenResponse.java
- backend/src/main/java/com/wooteco/nolto/exception/ErrorType.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/api/OAuthControllerTest.java
- backend/src/test/java/com/wooteco/nolto/auth/application/AuthServiceTest.java
- [간단한 SSR 이해하기](https://pomo0703.tistory.com/206)
- [간단한 쿠키 옵션 이해하기](https://pomo0703.tistory.com/207)
- [Refresh Token 적용 과정](https://pomo0703.tistory.com/208)
- 리프레시 토큰 발급에 대한 api 작성
- 리프레시 토큰 정상 발급
- 잘못된 리프레시 토큰으로 재발급 요청
- 잘못된 클라이언트 IP로 재발급 요청
- ErrorType 추가 (`auth-007`)
- 최대 메모리 사양 1G
- 최대 사용 메모리 초과 시 오래된 데이터를 지우고, 가장 최근 데이터를 저장하도록 설정
- 레포지토리에서는 redis를 사용하지 않으므로 다음과 같은 로그가 뜹니다.
```
Spring Data Redis - Could not safely identify store assignment for repository...
```
👉 `spring.data.redis.repositories.enabled =false` 로 설정하여 해결
- Closes #599 and #600
- 내장형 레디스를 이용해 테스트를 진행하려고 했으나 [M1에서 내장형 레디스 이슈](https://velog.io/@hakjong/ARM-Mac-M1-%EC%97%90%EC%84%9C-embedded-redis-%EC%82%AC%EC%9A%A9)로 우선 mocking
해당 글처럼 바이너리 파일을 가져와 프로젝트에 적용하려고 했으나 실패 ㅠㅠ 추후 재적용 논의필요!!
**로컬에서 redis 구동하여 제대로 작동하는 것은 …
> feat: refresh token을 통한 토큰 재발급

- backend/build.gradle
2.14.1 -> 2.15.0
실제 사용은 안하고 있지만 내부에 log4j2 라이브러리가 포함되어 있어(slf4j로 추정됨)
해당 버전이 2.14.1 버전이라 보안 이슈가 터진 버전으로 확인되어 2.15.1 버전으로 변경
Closes #702 
apache 주의 해주세요
> feat(log4j2): 구 버전의 보안 이슈로 log4j2 버전 변경
