woowacourse-teams/2021-nolto

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/domain/Like.java
- backend/src/main/java/com/wooteco/nolto/domain/Step.java
- backend/src/main/java/com/wooteco/nolto/domain/Tech.java
- backend/src/main/java/com/wooteco/nolto/domain/User.java
- backend/src/main/resources/application.properties
- 엔티티 클래스 작성
- User Entity
- Feed Entity
- Like Enitity
- Tech Entity
- lombok/validation 적용
- Getter, NoArgsConstructor
- NotNull, NotBlank
Closes #6 
- LIKE 엔티티는 예약어이므로, `Likes`로 테이블명 지정
> feat: 엔티티 클래스 정의

- frontend/.eslintrc.json
- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/.storybook/webpack.config.js
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/Global.styles.ts
- frontend/src/constants/palette.ts
- frontend/src/index.tsx
- frontend/tsconfig.json
- frontend/yarn.lock
Closes #15
버튼이 아직 안 예쁘게 보임. 곧 예쁠 예정 
아이콘 버튼은 따로 만들 예정
> feat: styled components, storybook 세팅 및 react entry point 설정

- frontend/src/components/@common/Button/Button.stories.tsx
- frontend/src/components/@common/Button/Button.styles.ts
- frontend/src/components/@common/Button/Button.tsx
- frontend/src/types.ts
> feat: Button 컴포넌트 구현

- frontend/src/components/@common/HighlightedText/HighlightedText.stories.tsx
- frontend/src/components/@common/HighlightedText/HighlightedText.styles.ts
- frontend/src/components/@common/HighlightedText/HighlightedText.tsx
HighlightedText 구현
Closes #30
간지나는 인생!
> feat: HighlightedText 구현

- backend/src/main/java/com/wooteco/nolto/AuthorizationException.java
- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/AuthenticationPrincipal.java
- backend/src/main/java/com/wooteco/nolto/auth/AuthenticationPrincipalConfig.java
- backend/src/main/java/com/wooteco/nolto/auth/MemberAuthenticationPrincipal.java
- backend/src/main/java/com/wooteco/nolto/auth/UserAuthenticationPrincipal.java
- backend/src/main/java/com/wooteco/nolto/auth/application/AuthService.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/AuthorizationExtractor.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/JwtTokenProvider.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/AuthController.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/AuthInterceptor.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/AuthenticationPrincipalArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/MemberArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/UserArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/TokenRequest.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/TokenResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/LikeService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Like.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/LikeRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedDetailResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedResponse.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedTest.java
- backend/src/test/java/com/wooteco/nolto/user/domain/UserTest.java
Closes #14 and Closes #26 Closes #20
- 좋아요 누르기 / 삭제 기능 구현
- auth에 관한 web-config 설정
* likes를 일급 컬렉션으로 싸려고 했으나, 일급 컬렉션이 마냥 좋은 것은 아니더라
* 다대다 중계 테이블에서는 일급 컬렉션 주의
* [참고](https://www.inflearn.com/questions/84874)
> feat: 좋아요 및 로그인 관련 WebConfig 추가

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/UserArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feeds.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/FilterStrategy.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/resources/application.properties
- backend/src/main/resources/logback-access.xml
- 핫 토이 피드 최신순으로 10개 조회
- Feeds 일급 컬렉션 생성
- Filter 를 FilterStrategy 로 변경
Closes #11 
#25 이슈 참고
> feat(hot-feeds): 핫 토이 피드 조회 기능 추가

- frontend/src/components/@common/Label/Label.stories.tsx
- frontend/src/components/@common/Label/Label.styles.ts
- frontend/src/components/@common/Label/Label.tsx
- frontend/src/constants/palette.ts
label 컴포넌트 만들었음
Closes #36
구구 좋아
> feat: form의 label 컴포넌트 구현 

- frontend/src/Global.styles.ts
- frontend/src/components/@common/Checkbox/Checkbox.stories.tsx
- frontend/src/components/@common/Checkbox/Checkbox.styles.ts
- frontend/src/components/@common/Checkbox/Checkbox.tsx
- frontend/src/components/@common/Label/Label.stories.tsx
- frontend/src/components/@common/Label/Label.styles.ts
- frontend/src/components/@common/Label/Label.tsx
- frontend/src/components/@common/TextArea/TextArea.stories.tsx
- frontend/src/components/@common/TextArea/TextArea.styles.ts
- frontend/src/components/@common/TextArea/TextArea.tsx
- frontend/src/components/@common/TextInput/TextInput.stories.tsx
- frontend/src/components/@common/TextInput/TextInput.styles.ts
- frontend/src/components/@common/TextInput/TextInput.tsx
- frontend/src/components/@common/Toggle/Toggle.stories.tsx
- frontend/src/components/@common/Toggle/Toggle.styles.ts
- frontend/src/components/@common/Toggle/Toggle.tsx
- frontend/src/constants/palette.ts
form에 들어갈 input 컴포넌트들 구현
Closes #37
밥 굶을 예정
> feat: form에 들어갈 input 컴포넌트들 구현

- frontend/.storybook/preview.js
- frontend/package.json
- frontend/src/Global.styles.ts
- frontend/src/components/LevelLinkButton/LevelLinkButton.stories.tsx
- frontend/src/components/LevelLinkButton/LevelLinkButton.styles.ts
- frontend/src/components/LevelLinkButton/LevelLinkButton.tsx
- frontend/yarn.lock
LevelLinkButton 컴포넌트 구현
- 3가지 상태로 구분
- selected일 때 눌리는 효과 (inner shadow)
Closes #45
맥, 윈도우 이모지 다름 
윈도우 못생김
> feat: LevelLinkButton 컴포넌트 구현

- frontend/.storybook/preview.js
storybook preview에서 BaseLayout 다시 삭제
> fix: storybook에 BaseLayout 삭제

- backend/src/main/resources/application.yml
- jpa properties 설정중 들여쓰기 문제로 인해 ddl-auto가 먹히지 않는 오류 해결
Closes #60 
- 들여쓰기를 잘합시다
- 수고했어요 조엘 포모 찰리 마찌
- 구구... 이래서 yml 쓰라고 하신건가요? ㅎㅎㅎ 감사합니당
> fix: yml 들여쓰기로 인한 오류 수정

- frontend/src/components/@common/IconButton/IconButton.tsx
- frontend/src/components/@common/TextButton/TextButton.tsx
버튼의 onClick이 동작하지 않는 문제가 있었습니다.
options를 Styled.Root로 넘겨주지 않아서 생긴 문제인것 같습니다.
해결하였습니다~
Closes #62
> fix: Button의 onClick이 동작하지 않는 문제

- backend/src/main/resources/application.yml
- yml 수정 후에도 로딩되지 않는 문제 해결
Closes #60 
- 아맞다 push 전 애플리케이션 실행
> fix: application yml 수정

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- 서버를 재 구동 시켜도 dataloader가 작동하지 않도록 변경
- 사실 여기에는 실수가 있어...
- 아맞다 push 전 브랜치 확인
- 배고프면 쉬자
> refactor: prod 환경에서는 data-loader가 작동하지 않도록 변경

- frontend/.eslintrc.json
> [FE]fix: eslint 설정이 잘못되어있었던 문제 수정

- frontend/src/commonStyles.ts
- frontend/src/components/@common/FileInput/FileInput.stories.tsx
- frontend/src/components/@common/FileInput/FileInput.styles.ts
- frontend/src/components/@common/FileInput/FileInput.tsx
- frontend/src/components/@common/HighlightedText/HighlightedText.tsx
- frontend/src/components/@common/Label/Label.styles.ts
- frontend/src/components/@common/Label/Label.tsx
- frontend/src/components/@common/Toggle/Toggle.styles.ts
- frontend/src/components/LoginModal/LoginModal.tsx
- frontend/src/pages/Upload/Upload.stories.tsx
- frontend/src/pages/Upload/Upload.styles.ts
- frontend/src/pages/Upload/Upload.tsx
일단.... 겉으로는 멀쩡하지만 마크업 구조는 **매우매우매우매우✨** 복잡합니다.....😭
생각보다 쉽지 않네요 나중에 리팩터링 하면서 정리 좀 해야겠어요 ㅠㅜ
- FileInput 컴포넌트 구현 : <input type="file" /> 컴포넌트가 없더라구용 만들었습니다.
- FlexContainer 구현 : wrapper들 이름짓는게 너무 힘들어서 만들어봤습니다.
- Upload 페이지 컴포넌트 구현
Closes #73 
주의: 실제로는 훨씬 큼
전반적으로 UI가 좀 큰 경향이 있네요ㅠ 나중에 수정을 좀 해야할듯
> [FE] Upload 페이지 컴포넌트 구현

- backend/src/main/java/com/wooteco/nolto/WebConfig.java
- WebConfig 클래스 생성
Closes #89 
- CORS 설정에 모든 도메인을 허용해놓은 상황
> feat(CORS): CORS 설정 추가

- backend/src/main/resources/application.yml
- image urldp https 명시가 빠져 바로 접근 불가한 오류 해결
Closes #96 
- 동일하게 검증 필요
> hotfix(): cloud-front url에 https 명시

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/constants/routes.ts
- frontend/src/hooks/useHotFeeds.ts
- frontend/src/hooks/useRecentFeeds.ts
- frontend/src/pages/Home/Home.stories.tsx
- frontend/src/pages/Home/Home.tsx
- frontend/webpack.config.js
- frontend/yarn.lock
hot feeds, recent feeds를 가져와서 보여주고 있읍니다
Closes #99
은 CSS 수정되면~
hot feeds, recent feeds를 가져와서 보여줘야 해요 ❗️❗️
> [FE] hot feeds, recent feeds를 가져와서 보여줘야 해요

- backend/src/main/java/com/wooteco/nolto/auth/ui/AuthController.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- 작성한 DTO에 대한 validation 추가
- DTO를 만들어 두고, 정작 `@Valid`로 검증하지 않았음
Closes #86
> feat: DTO validation 추가

- backend/src/main/java/com/wooteco/nolto/ErrorResponse.java
- backend/src/main/java/com/wooteco/nolto/ExceptionAdvice.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/TokenRequest.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- 예외 처리 핸들러 구현
- 우선 모든 에러를 400 BadRequest로 처리
- message로 예외 발생 이유 작성해둠
Closes #104 
- 다음 스프린트에 예외 처리 전략 상의할 예정
> feat: 예외 처리 핸들러 구현

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/Global.styles.ts
- frontend/src/index.tsx
- frontend/webpack.config.js
- frontend/yarn.lock
- webpack historyApiFallback 설정
- GlobalStyle 위치 이동
- react-query-devtools 설치
> [FE] chore: 환경 설정 추가

- backend/src/main/resources/application.yml
- JPA ddl-auto update로 변경
- 찰리/포모 코드 변경시 추후 논의
> fix: JPA ddl-auto update로 변경

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedTechService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/FeedTech.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/FeedTechRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/Tech.java
- backend/src/main/java/com/wooteco/nolto/tech/ui/dto/TechResponse.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedRepositoryTest.java
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedTest.java
- backend/src/test/java/com/wooteco/nolto/user/domain/UserTest.java
- TechResponse Getter 추가
- TechRequest에 Tech Id를 받도록 수정
- List<Long> techs
- DataLoader 에서 Feed 추가 후 Feed에 Tech를 포함시키도록 추가
#92 주의사항 이슈 해결
- TechRepository 테스트 save() 만 추가
- 이후 추가 필요
> feat: feed tech 연관관계 매핑

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- 더미 데이터를 초기화 해줘야해서 변경
- 이후 DataLoader 적용 파일에서 prod 를 빼야함
> fix(DataLoader): DataLoader prod 설정에도 적용되도록 변경

- frontend/src/App.tsx
- frontend/src/components/StretchCard/StretchCard.tsx
- frontend/src/constants/common.ts
- frontend/src/constants/routes.ts
- frontend/src/hooks/queries/useFeedDetail.ts
- frontend/src/pages/FeedDetail/FeedDetail.styles.ts
- frontend/src/pages/FeedDetail/FeedDetail.tsx
- frontend/src/pages/Home/Home.tsx
- frontend/src/types.ts
- frontend/webpack.config.js
feat: FeedDetail 정보 보여주기
Closes #120
> [FE] feat: FeedDetail 정보 보여주기

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/MemberArgumentResolver.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedTechService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/LikeService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedTechRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/LikeRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/wooteco/nolto/feed/domain/FeedRepositoryTest.java
- FeedRequest의 techs 리스트 초기화 추가
- member argument resolver의 credentials 수정
- prod profile의 auto-ddl, data loader 설정 변경
> fix: post 요청 에러 수정

- backend/src/main/java/com/wooteco/nolto/WebConfig.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- 잦은 머지 죄송합니다 22
- 메서드 이름이 변경 되지 않은 부분 까지 수정 완료 😭
- 아 맞다 push 전 테스트 코드 돌려보기
> fix: techs 이름 수정이 잘못됨

- frontend/src/components/@common/FileInput/FileInput.styles.ts
- frontend/src/components/@common/FormInput/FormInput.styles.ts
- frontend/src/components/@common/Label/Label.styles.ts
- frontend/src/components/@common/RadioButton/RadioButton.styles.ts
- frontend/src/components/@common/TextArea/TextArea.styles.ts
- frontend/src/components/@common/Toggle/Toggle.styles.ts
- frontend/src/components/TechInput/TechInput.stories.tsx
- frontend/src/components/TechInput/TechInput.styles.ts
- frontend/src/components/TechInput/TechInput.tsx
- frontend/src/hooks/queries/useTechs.ts
- frontend/src/pages/Upload/Upload.styles.ts
- frontend/src/pages/Upload/Upload.tsx
- `TechInput` 컴포넌트 구현
- feed 업로드 시 tech 배열 함께 전송
- 업로드 페이지 input 사이즈 작게 조정
Closes #130 
- SOS 버튼 정렬 조정 필요
> [FE] feed 업로드 시 tech 배열 함께 전송

- frontend/src/pages/FeedDetail/FeedDetail.styles.ts
- frontend/src/pages/FeedDetail/FeedDetail.tsx
> [FE] refactor: FeedDetail 페이지 요소 크기 작게 조정

- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Searchbar/Searchbar.styles.ts
- frontend/src/components/Searchbar/Searchbar.tsx
- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Home/Home.tsx
header의 search icon 클릭 시 searchbar 열리는 기능 구현
- Home의 searchbar import 방식 수정
- searchbar 폰트 사이즈 수정
Closes #134
약간의 버벅임
> [FE] feat: header의 search icon 클릭 시 searchbar 열리는 기능 구현

- frontend/src/App.tsx
- frontend/src/constants/api.ts
- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/RecentFeeds/RecentFeeds.stories.tsx
- frontend/src/pages/RecentFeeds/RecentFeeds.styles.ts
- frontend/src/pages/RecentFeeds/RecentFeeds.tsx
> [FE] feat: RecentFeeds 페이지 구현

- frontend/public/netlify.toml
Closes #153
chore: netlify routing을 위한 파일 설정
> [FE] chore: netlify routing을 위한 파일 설정

- frontend/src/pages/FeedDetail/FeedDetail.styles.ts
피드 상세 페이지의 콘텐츠 개행을 위한 태그 변경(pre 태그)
Closes #162
`refactor` 아니고 `pre` 인 것 같음
> [FE] refactor: 피드 상세 페이지의 콘텐츠 개행을 위한 태그 변경(pre 태그)

- frontend/src/components/RegularCard/RegularCard.styles.ts
- frontend/src/components/TechChip/TechChip.styles.ts
- frontend/src/constants/common.ts
> [FE] fix: 조립중 단계 칩이 '진행중'이라 표시되던 문제 수정

- frontend/src/pages/Upload/Upload.styles.ts
- 제출, 취소 버튼 사이즈 증가
- input에 box-shadow 추가
> [FE] fix: Upload 페이지 레이아웃 수정

- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/RegularCard/RegularCard.styles.ts
- frontend/src/components/StretchCard/StretchCard.styles.ts
- frontend/src/components/StretchCard/StretchCard.tsx
fix: Feed 내용이 많을 시 Card에서 내용이 넘쳐보이는 버그 수정
Closes #165
> [FE] fix: Feed 내용이 많을 시 Card에서 내용이 넘쳐보이는 버그 수정

- frontend/src/pages/FeedDetail/FeedDetail.styles.ts
- frontend/src/pages/FeedDetail/FeedDetail.tsx
FeedDetail 페이지 비율 축소
데모데이 직전 급하게 수정
> [FE] refactor: FeedDetail 페이지 비율 축소

- backend/src/test/java/com/wooteco/nolto/api/FeedControllerTest.java
> fix(): api 문서 수정

- backend/src/main/java/com/wooteco/nolto/auth/application/AuthService.java
- Optional orElse() 하는 부분에서 orElseGet() 으로 변경
Closes #186
> fix: Oauth login 로직 수정

- frontend/src/App.tsx
- frontend/src/components/TechInput/TechInput.tsx
- frontend/src/hooks/@common/useQueryDebounce.ts
TechInput debounce 구현
Closes #188
> [FE] feat: TechInput debounce 구현

- frontend/src/App.tsx
- frontend/src/components/AsyncBoundary.tsx
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/hooks/queries/useHotFeeds.ts
- frontend/src/pages/Home/Home.tsx
- frontend/src/utils/CustomError.ts
- frontend/src/utils/HttpError.ts
feat: ErrorBoundary, Suspense 구현
Closes #199
은 없는 기능!
이틀 꼬박 커밋 메시지보다 엄청난 일들을 함
> [FE] feat: ErrorBoundary, Suspense 구현

- backend/build.gradle
- backend/src/main/resources/application.yml
- backend/src/main/resources/db/migration/V1__init.sql
- 환경 설정별 flyway 적용 여부 설정
- flyway 의존성 추가 
- dev에 데이터 백업 csv 별도 저장
Closes #190 
- flyway 설정을 main으로 병합 시 테이블 초기화 필요
> feat(): flyway 초기 설정 적용

- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
> fix: feed 업로드 시 이미지 수정이 안되는 버그 수정

- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
- local: console-logging, info-level
- dev: file-info-logging
- prod: file-error-logging
Closes #244
- 더 구체적인 로깅 정책 논의와 반영 필요 
- 계속 푸쉬할 예정
> feat(): 로깅 전략에 따른 로깅 설정

- backend/src/main/java/com/wooteco/nolto/feed/domain/FilterStrategy.java
- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
> fix: 예외 코드 수정

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
> feat: 인수테스트를 위한 설정 파일 추가

- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/components/SearchResultContent/SearchResultContent.styles.ts
- frontend/src/components/SearchResultContent/SearchResultContent.tsx
- frontend/src/components/SearchResultHeader/SearchResultHeader.styles.ts
- frontend/src/hooks/queries/useSearch.ts
- frontend/src/pages/RecentFeeds/RecentFeeds.styles.ts
- frontend/src/pages/SearchResult/SearchResult.styles.ts
- frontend/src/pages/SearchResult/SearchResult.tsx
검색 결과 페이지에서 피드 상태로 필터링 기능 구현
Closes #246 
CSS가 조금 불안정함
> [FE] feat: 검색 결과 페이지에서 피드 상태로 필터링 기능 구현

- frontend/src/components/CroppedEllipse/CroppedEllipse.styles.ts
- frontend/src/context/techTag/input/TechInput.styles.ts
- frontend/src/pages/Modify/Modify.tsx
fix: uploadform의 techinput 가리는 버그 수정
Closes #252
말에 hover 해보세요
> [FE] fix: uploadform의 techinput 가리는 버그 수정

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/AuthenticationPrincipalConfig.java
- AuthenticationPrincipalConfig 에 Resolver 등록해줌
Closes #264
- 폰 리졸버 주의
> fix(Resolver) : UserArgumentResolver 등록

- frontend/src/components/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/components/LikeButton/LikeButton.tsx
- frontend/src/constants/errorCodeMap.ts
- frontend/src/hooks/mutations/useFeedDelete.ts
- frontend/src/hooks/mutations/useFeedLike.ts
- frontend/src/hooks/mutations/useFeedModify.ts
- frontend/src/hooks/mutations/useFeedUnlike.ts
- frontend/src/hooks/mutations/useFeedUpload.ts
- frontend/src/hooks/queries/useFeedDetail.ts
- frontend/src/hooks/queries/useHotFeeds.ts
- frontend/src/hooks/queries/useMember.tsx
- frontend/src/hooks/queries/useRecentFeeds.ts
- frontend/src/hooks/queries/useSearch.ts
- frontend/src/hooks/queries/useTechAutoComplete.ts
- frontend/src/hooks/queries/useTechs.ts
- frontend/src/types.ts
- frontend/src/utils/HttpError.ts
- frontend/src/utils/error.ts
- frontend/src/utils/typeGuard.ts
- 글 작성자가 아닐 시 글 수정, 삭제 불가
- 타입 가드를 사용해 좀 더 타입 추론이 잘되도록 수정
- 좋아요 에러 코드에 따른 행동 분기
Closes #273
> [FE] 좋아요 에러 코드에 따른 행동 분기 처리, 글 작성자가 아닐 시 글 수정, 삭제 불가

- frontend/src/App.tsx
- frontend/src/components/PrivateRoute.tsx
- frontend/src/utils/error.ts
- frontend/src/utils/typeGuard.ts
feat: 로그인한 유저만 접속 가능한 PrivateRoute 구현
- error, typeGuard에 typescript-no-implicit-any 타이핑 disable 및 unknown으로 수정
Closes #275
만족스러움
> feat: 로그인한 유저만 접속 가능한 PrivateRoute 구현

- frontend/src/components/Header/Header.tsx
> feat: 조엘의 웹 호스팅 추가

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/FeedRequest.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/TechValid.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/TechValidator.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- 기술 스택 중복에 대한 validation 적용
- 피드 업데이트 시 테크 수정 관련 기능 리팩토링
> [BE] 기술 스택 중복에 대한 validation 적용

- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/TechValidator.java
- cascade 고아 객체 적용
- feedService에서 feedtechRepository 삭제
> refactor: cascade 고아 객체 적용

- backend/src/main/java/com/wooteco/nolto/tech/application/TechService.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/TechRepository.java
- backend/src/main/java/com/wooteco/nolto/tech/ui/TechController.java
- 인기있는 기술 스택 조회 기능 추가
- `GET /tags/techs/trend`
- Closes #289 
- JPQL 쉽지 않네,, limit을 쓸수가 없잖아!!!!!!!!! (feat. 조엘)
,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어어엌!!!!!!! ,༼;´༎ຶ۝༎ຶ༽우워어어어
> feat: 인기있는 기술 스택 조회 기능 추가

- backend/build.gradle
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
- logging level error에 대해 슬랙 연동 알람을 설정
- 컬러 로깅 출력 설정
Closes #22 
- 최고야 
- 우리 에러 슬랙은 비공개임
> feat(): logging-level error에 대한 슬랙 연동 알림 설정

- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- ERROR 레벨에 스택 트레이스까지 찍혀 슬랙 알람 너무 많이 오는 문제 임시방편 해결
- 명수형 멈춰
- 에러 로깅에 대해 내일 다시 이야기해보기
> feat(): 스택 트레이스만 WARN 레벨로 설정

- frontend/src/components/FeedDetailContent/FeedDetailContent.tsx
피드 상세 페이지에서 기술스택 클릭으로 검색할 수 있게끔 구현했습니다
Closes #310
> [FE] feat: 피드 상세 페이지에서 기술스택 클릭으로 검색

- frontend/custom.d.ts
- frontend/src/components/@common/HighlightedText/HighlightedText.styles.ts
- frontend/src/components/@common/HighlightedText/HighlightedText.tsx
- frontend/src/components/@common/IconButton/IconButton.stories.tsx
- frontend/src/components/@common/IconButton/IconButton.styles.ts
- frontend/src/components/@common/IconButton/IconButton.tsx
- frontend/src/components/@common/ToggleList/ToggleList.stories.tsx
- frontend/src/components/@common/ToggleList/ToggleList.styles.ts
- frontend/src/components/@common/ToggleList/ToggleList.tsx
- frontend/src/components/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/components/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/Header/Header.tsx
- frontend/src/components/HotFeedsContent/HotFeedsContent.styles.ts
- frontend/src/components/HotFeedsContent/HotFeedsContent.tsx
- FeedDetail 스타일 전반적인 수정
- ToggleList 컴포넌트 구현
- 뷰포트가 줄어들 때 IconButton 크기가 쪼그라드는 현상 수정
Closes #312
아직 ToggleList가 완벽하진 않은듯. 조금 더 이뻤으면 좋겠습니당
> [FE] FeedDetail 스타일 전반적인 수정, ToggleList 컴포넌트 구현

- frontend/src/components/FeedUploadForm/FeedUploadForm.styles.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/pages/Modify/Modify.styles.ts
- frontend/src/pages/Upload/Upload.styles.ts
refactor: 피드 업로드 폼 디자인 수정
안 예쁘면 철회
> [FE] refactor: 피드 업로드 폼 디자인 수정

- frontend/src/commonStyles.ts
- frontend/src/components/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/components/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/utils/error.ts
- 잘못된 end point로 요청 시 스낵바가 뜨지 않던 현상 수정
- feedDetail 스타일 살짝 수정
Closes #321
> [FE] 잘못된 end point로 요청 시 스낵바가 뜨지 않던 현상 수정 

- frontend/src/pages/About/About.tsx
> [FE] fix: made를 make로 변경

- frontend/src/components/@common/FileInput/FileInput.tsx
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/components/TeamMember/TeamMember.tsx
- frontend/src/components/UserProfile/UserProfile.styles.ts
- frontend/src/context/modal/ModalProvider.tsx
fix: v2.0 QA 버그 픽스
- 로그인창 x 버튼 키우기
- 놀토 팀 개인 사이트 링크 수정
- 피드 업로드 시 확장자 체크
- 프로필의 로그아웃 버튼 애니메이션 수정
> [FE] fix: v2.0 QA 버그 픽스

- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
- backend/src/main/resources/db/migration/V2__change_feed_content_type.sql
- 인기있는 기술 스택 목록 조회 기능 추가
- 매핑 url에 정규 표현식 적용
- Close #327 and Close #328
> 피드의 "content" 컬럼 타입 수정 및 feed 매핑 url에 정규 표현식 적용

- backend/src/main/java/com/wooteco/nolto/BaseEntity.java
- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/feed/application/FeedService.java
- backend/src/main/java/com/wooteco/nolto/feed/application/LikeService.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/CommentLike.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/CommentRepository.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/Tech.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- backend/src/main/resources/db/migration/V3__add_comment.sql
- backend/src/main/resources/db/migration/V4__change_modified_not_null.sql
- 댓글(Comment) 엔티티 작성 및 flyway 스크립트 추가
- Cascade 전체적으로 수정 (User 가 전체적인 관리를 하도록)
Closes #334
Cascade 에 주의하면서 코드 작성
열정열정~~
> feat(comment): 댓글 엔티티 작성 및 flyway 스크립트 추가

- backend/src/main/java/com/wooteco/nolto/feed/application/CommentService.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/CommentController.java
- CommentService 작성
- CommentController 작성ㅇ
Closes #338
> feat(comment): CommentService, CommentController 작성

- backend/src/main/java/com/wooteco/nolto/feed/application/LikeService.java
- backend/src/test/java/com/wooteco/nolto/acceptance/FeedAcceptanceTest.java
- LikeRepository로 delete할 수 있도록 설정해두었습니다.
- Close #376 
- 추후에 바뀔 수 있습니다.
> fix: 좋아요 취소 버그 수정

- frontend/src/commonStyles.ts
- frontend/src/components/@common/FileInput/FileInput.styles.ts
- frontend/src/components/@common/IconButton/IconButton.styles.ts
- frontend/src/components/@common/TextButton/TextButton.styles.ts
- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/LevelButton/LevelButton.styles.ts
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.styles.ts
- frontend/src/components/RegularCard/RegularCard.styles.ts
- frontend/src/components/StretchCard/StretchCard.styles.ts
- frontend/src/components/UserProfile/UserProfile.styles.ts
- frontend/src/pages/Home/Home.styles.ts
- frontend/src/pages/Mypage/History/History.styles.ts
- frontend/src/pages/Mypage/Intro/Intro.styles.ts
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.styles.ts
- header nav item hover 시 트랜지션
- button 등의 요소 hover 시 layer 주는 트랜지션 commonStyle로 분리
티는 별로 안 나겠지만 확실히 부드러워짐!
> [FE] 각종 CSS 트랜지션 작성, commonStyle로 분리 

- frontend/src/components/TrendTechs/TrendTechs.stories.tsx
- frontend/src/components/TrendTechs/TrendTechs.styles.ts
- frontend/src/components/TrendTechs/TrendTechs.tsx
- frontend/src/hooks/queries/useTrendTechs.ts
- frontend/src/pages/Home/Home.tsx
Trend 기술스택 컴포넌트 분리 & api 연동
Closes #363
이곳에서 suspense는 과하다고 생각하여 `suspense: false` 걸어줌
> [FE] Trend 기술스택 컴포넌트 분리 & api 연동

- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/components/Skeleton/Skeleton.stories.tsx
- frontend/src/components/Skeleton/Skeleton.styles.ts
- frontend/src/components/Skeleton/Skeleton.tsx
- frontend/src/components/StretchCard/StretchCard.styles.ts
- frontend/src/constants/palette.ts
feat: 피드 skeleton ui 구현
Closes #372
잠시 네트워크 느리게 해서 저렇게 느리게 보임 (실제로는 순식간)
> [FE] feat: 피드 skeleton ui 구현

- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/CommentLike.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceFixture.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- 실패하던 테스트 수정
```java
@DisplayName("댓글 삭제시 댓글의 대댓글도 함께 삭제된다.")
@Test
void deleteComment() {
```
아 맞다 테스트..
> fix(comment): 댓글 삭제 테스트 중 실패하던 것 수정

- frontend/jest.config.js
- frontend/src/components/LikeButton/LikeButton.stories.tsx
- frontend/src/components/LikeButton/LikeButton.test.tsx
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.test.tsx
FeedDetailContent, LikeButton 유닛 테스트
> [FE] test: FeedDetailContent, LikeButton 테스트

- frontend/src/__mocks__/fixture/Feeds.ts
- frontend/src/components/@common/Label/Label.tsx
- frontend/src/components/FeedUploadForm/FeedUploadForm.test.tsx
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- FeedUploadForm 테스트
- 테스트 코드 짜다보니 label 관련해서 웹접근성을 지키게 됨(!)
> [FE] test: FeedUploadForm 테스트

- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/CommentRepository.java
- backend/src/test/java/com/wooteco/nolto/acceptance/CommentAcceptanceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
> fix(comment&reply): 커밋 안된 부분 추가

- backend/build.gradle
- jacoco gradle을 통해 코드 커버리지를 분석한다
- 현재 jacocoTestCoverageVerification의 minimum을 0으로 임시설정
> feat: jacoco gradle 추가

- frontend/src/components/@common/Loading/Loading.tsx
- frontend/src/components/CommentModule/@common/Comment/Comment.tsx
- frontend/src/components/CommentModule/CommentModule.tsx
- frontend/src/hooks/queries/profile/useNotiLoad.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/pages/Mypage/Notification/Notification.styles.ts
- frontend/src/pages/Mypage/Notification/Notification.tsx
- frontend/src/types.ts
feat: Mypage 알림 클릭 시 해당 피드(또는 댓글)로 이동
Closes #410
giphy 에러
> [FE] feat: Mypage 알림 클릭 시 해당 피드(또는 댓글)로 이동

- backend/build.gradle
- 클래스 단위로 테스트
- 라인 커버리지 0.7 이상
- 브랜치 커버리지 0.7 이상 
- image, oauth 패키지는 excludes
> feat: jacoco rule 추가

- frontend/src/pages/Mypage/History/History.styles.ts
> [hotifx] fix: 윈도우에서 profile 글자 깨짐 현상 수정

- backend/src/main/java/com/wooteco/nolto/user/application/MemberService.java
- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
- refactor: History 최신순으로 반환하도록 수정
- 깨지는 테스트코드 (순서관련) 수정
> refactor: History 최신순으로 반환하도록 수정

- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
- fix: comment 한번에 저장되는 이슈 thread.sleep(1)으로 해결
> fix: comment 한번에 저장되는 이슈 thread.sleep(1)으로 해결

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/domain/SocialOAuthInfo.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/AuthorizationExtractor.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/GithubClient.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/GithubOAuthInfo.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/GoogleClient.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/GoogleOAuthInfo.java
- backend/src/main/java/com/wooteco/nolto/auth/infrastructure/oauth/OAuthClientDetail.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/dto/OAuthRedirectResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Comment.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feed.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Like.java
- backend/src/test/java/com/wooteco/nolto/acceptance/CommentAcceptanceTest.java
- final static -> static final 같은 당연한 부분들을 수정 (함께 의견을 나눠야하는 부분은 그대로 뒀슴당)
- 중복된 테스트 최소화
- 테스트 Fixture 만들어서 테스트 코드 중복을 없애기
- 인수테스트의 흐름을 잘 파악할 수 있게 수정
Closes #416
Closes #418
- 실수 안할게요 ㅠㅠ..
> refactor: 소나 큐브 코드 스멜에 나온 간단한 수정 사항들 반영

- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
- saveAndFlush를 통해 저장 순서 보장하여 테스트하도록 수정
- 이전 테스트코드는 user의 cascade를 통해 피드/커멘트/라이크 저장하도록 함
- 우다다다 저장되어 저장 순서를 알수없는 문제 발생
- 따라서 필요한 리포지토리 다 끌어온 후, 피드/커멘트/라이크 하나하나 순서대로 저장하도록 beforeEach구성
- 까스케이드 == 까스라이팅?
> fix(MemberServiceTest): saveAndFlush를 통해 저장 순서 보장하여 테스트하도록 수정

- backend/src/test/java/com/wooteco/nolto/user/application/MemberServiceTest.java
> hotfix: 임시 테스트 돌아가게 수정

- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- 파일명 생성 시 UUID로 생성하도록 변경
- 해당 부분 소나린트 컨벤션 적용
Closes #432
> fix(): 이미지 파일 이름 생성 시 uuid를 쓰도록 변경

- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/CommentRepository.java
- backend/src/main/java/com/wooteco/nolto/user/application/MemberService.java
- backend/src/test/java/com/wooteco/nolto/BaseEntityTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceFixture.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
- createdDate 최신순으로 우선 정렬하고, 같을 경우 id 순으로 내림차 정렬하도록 수정
- `Thread.sleep` 제거
- Closes #434 
- 영상이 분노 가라앉히기
> refactor: thread sleep 제거 

- backend/build.gradle
- backend/src/main/resources/application.yml
- yml 설정
- spring actuator
Closes #438
- 원하는대로 동작하는지 확인 필요
> feat(): cloud-watch 연동을 위한 애플리케이션 설정 추가

- backend/build.gradle
- backend/src/main/resources/application.yml
> fix(): yml 오류 수정

- frontend/src/components/@common/AutoHeightTextArea/AutoHeightTextArea.styles.ts
- frontend/src/components/@common/AutoHeightTextArea/AutoHeightTextArea.tsx
- frontend/src/components/CommentModule/@common/Comment/Comment.styles.ts
- frontend/src/components/CommentModule/@common/Comment/Comment.tsx
- frontend/src/components/CommentModule/@common/CommentForm/CommentForm.styles.ts
- frontend/src/components/CommentModule/@common/CommentForm/CommentForm.tsx
- frontend/src/components/CommentModule/SubCommentModule/SubCommentModule.styles.ts
- frontend/src/components/CommentModule/SubCommentModule/SubCommentModule.tsx
- frontend/src/contexts/snackbar/SnackbarProvider.styles.ts
> [FE] 댓글을 여러줄로 작성할 수 있도록 수정

- frontend/package.json
- frontend/webpack.config.js
- frontend/yarn.lock
> [FE] chore: gzip 관련 플러그인 설치

- backend/src/main/resources/logback-spring.xml
- cloudwatch에서 parse를 하기 위해 우선 임시 삭제
> refactor: info/error log 컬러 제거

- frontend/package.json
- frontend/webpack.config.js
- frontend/yarn.lock
Reverts woowacourse-teams/2021-nolto#446
> Revert "[FE] chore: gzip 관련 플러그인 설치"

- frontend/src/components/Header/Header.styles.ts
- frontend/src/components/TrendTechs/TrendTechs.styles.ts
- frontend/src/pages/About/members.ts
> [FE] fix: 윈도우에서 깨지는 레이아웃 수정

- backend/src/main/java/com/wooteco/nolto/DataLoader.java
- backend/src/main/java/com/wooteco/nolto/auth/ui/AuthInterceptor.java
- backend/src/main/java/com/wooteco/nolto/exception/dto/ExceptionResponse.java
- backend/src/main/java/com/wooteco/nolto/feed/application/searchstrategy/SearchStrategy.java
- backend/src/test/java/com/wooteco/nolto/feed/application/CommentServiceTest.java
- AuthInterceptor 분기들 메서드로 변경
- SearchStrategy 생성자 접근제어자를 public -> protected 로 변경
- defaultImage 상수 static final 로 변경
- CommentServiceTest 에 남아있던 Thread.sleep() 제거
Closes #449
- 제거 못한 악취들은 의견을 좀 나눠봐야 할 것 같아요 ㅠㅠ
> refactor(): 전체적인 코드 리팩토링

- backend/build.gradle
- backend/src/main/java/com/wooteco/nolto/exception/ControllerAdvice.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/local-file-logger.xml
- backend/src/main/resources/logback-spring.xml
-  cloudwatch 의존성 제거
- file sql logging 추가
- 에러 로그 한줄 출력되도록 수정
- Closes #461
> feat: sql 에러 로그 추가

- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- 생성자에서 bio 필드가 null일 경우 ""로 값을 주도록 변경
> fix(user): bio 필드가 null일 경우 ""로 값을 주도록 변경

- frontend/src/__tests__/hooks/useFeedDelete.test.tsx
> [FE] refactor: hook test 경로 수정

- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/Mypage/History/History.tsx
- frontend/src/pages/Mypage/Notification/Notification.styles.ts
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.tsx
- frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.styles.ts
- frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.tsx
- 오타 삭제
- 페이지 이동 간 스크롤 원상복귀
- 검색 페이지에서 빈 값 검색 시 검색 방지
> [FE] fix: 데모데이 전 최종 버그 수정

- frontend/src/pages/Mypage/Notification/Notification.styles.ts
fix: 모두읽음으로 표시 => 윈도우에서 깨지는 현상 수정
> [FE] fix: 모두읽음으로 표시 => 윈도우에서 깨지는 현상 수정

- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
> fix: resizedFile 객체 삭제

- README.md
- 프로젝트 소개
- 팀원 소개
- 기술 태그 뱃지
Closes #301 
- 함께 더 의논해봅시다
> docs(): 놀토 리드미 초안 작성

- frontend/src/components/ErrorFallback/ErrorFallback.styles.ts
- frontend/src/components/ErrorFallback/ErrorFallback.tsx
ErrorFallback 디자인 깔끔하게 변경
Closes #485
통통 튀어요
> refactor: ErrorFallback 디자인 변경

- frontend/src/components/HotFeedsContent/HotFeedsContent.tsx
- frontend/src/components/LargeFeedCard/LargeFeedCard.tsx
- frontend/src/components/LargeSkeleton/LargeSkeleton.stories.tsx
- frontend/src/components/LargeSkeleton/LargeSkeleton.styles.ts
- frontend/src/components/LargeSkeleton/LargeSkeleton.tsx
- frontend/src/components/RegularFeedCard/RegularFeedCard.styles.ts
- frontend/src/components/RegularFeedCard/RegularFeedCard.tsx
- frontend/src/components/RegularSkeleton/RegularSkeleton.stories.tsx
- frontend/src/components/RegularSkeleton/RegularSkeleton.styles.ts
- frontend/src/components/RegularSkeleton/RegularSkeleton.tsx
- frontend/src/pages/Home/HomeFeedsContent/HomeFeedsContent.tsx
스켈레톤 UI 새로 만들기
Closes #499
- 내가 500번이지롱 
- 코드중복 많음 ㅎㅎ ㅠ
> [FE] 스켈레톤 UI 새로 만들기

- frontend/src/commonStyles.ts
- frontend/src/components/@common/Chip/Chip.styles.ts
- frontend/src/constants/mediaQuery.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
> [FE] 피드 상세 페이지 반응형 구현

- frontend/.gitignore
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/constants/message.ts
- frontend/src/index.tsx
- frontend/src/utils/typeGuard.ts
- frontend/webpack.config.js
- frontend/yarn.lock
- sentry 세팅
- http 에러가 아닌 경우 유저 리포트를 제출하게끔
Closes #506
- woowacourse 슬랙 앱 제한 떠서 프론트용 워크스페이스 새로 팜
> [FE] sentry 세팅

- backend/src/main/java/com/wooteco/nolto/WebConfig.java
- backend/src/main/resources/application.yml
- profile 별 cors의 allow-origin을 다르게 하도록 변경
- origin을 yml 에서 관리
Closes #509
> feat(): profile 별 cors의 allow-origin을 다르게 하도록 변경

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/UserProfile/UserProfile.tsx
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/index.ts
- frontend/tsconfig.json
- frontend/webpack.common.js
- frontend/webpack.dev.js
- frontend/webpack.prod.js
- frontend/yarn.lock
loadable로 코드 스플리팅, SENTRY_DSN 설정
Closes #514
> [FE] loadable로 코드 스플리팅, SENTRY_DSN 설정

- frontend/webpack.dev.js
- frontend/webpack.prod.js
fix: bundle analyzer prod에서 제거
바보같은 실수!!
> [FE] fix: bundle analyzer prod에서 제거

- frontend/src/constants/api.ts
- frontend/webpack.common.js
> [FE] chore: api endpoint가 환경변수에 따라 변경 가능

- backend/src/main/java/com/wooteco/nolto/TomcatWebCustomConfig.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/Feeds.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/FilterStrategy.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedTechRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/domain/repository/LikeRepository.java
- backend/src/main/java/com/wooteco/nolto/feed/ui/dto/CommentResponse.java
- backend/src/main/java/com/wooteco/nolto/notification/application/NotificationFeedDeleteEvent.java
- backend/src/main/java/com/wooteco/nolto/tech/domain/TechValidator.java
- backend/src/main/java/com/wooteco/nolto/user/domain/User.java
- Tech 검색 시 Feed도 한번에 조회되도록 패치 조인 적용
Closes #536 
- 소나린트에서 잡아주는 코드 스멜 일부 수정
> Refactor: jpa의 n+1 문제 수정

- frontend/src/components/@common/Dropdown/Dropdown.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/components/SearchOption/SearchOption.tsx
- frontend/src/components/UserProfile/UserProfile.tsx
- frontend/src/contexts/techTag/input/TechInput.tsx
- frontend/src/hooks/@common/useFocusOut.ts
- frontend/src/hooks/@common/useIntersectionObserver.ts
- frontend/src/hooks/queries/feed/useRecentFeedsLoad.ts
- frontend/src/pages/Mypage/History/History.tsx
- frontend/src/utils/common.ts
- intersection observer의 stale closure 문제 해결
- observer가 null을 unobserve 하고 있던 문제 해결
- focus out 컨트롤 훅 구현
Closes #551
https://media.giphy.com/media/LLsYb2ToUgj1eGxurs/giphy.gif?cid=790b76111d97720868da7dddc4456038f6e8ff21c04e471c&rid=giphy.gif&ct=g
> [FE] focus out 컨트롤 훅 구현

- frontend/package.json
- frontend/src/commonStyles.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.styles.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/constants/palette.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/pages/Modify/Modify.styles.ts
- frontend/src/pages/Modify/Modify.tsx
- frontend/src/pages/Upload/Upload.styles.ts
- frontend/src/pages/Upload/Upload.tsx
- frontend/yarn.lock
마크다운 기능 구현
Closes #547
테스트가 죽어도 안 돌아가서 (import문 충돌만 2시간째 해결중) 일단 그냥 올림
> [FE] 마크다운 기능 

- frontend/src/hooks/queries/feed/useRecentFeedsLoad.ts
- frontend/src/hooks/queries/useSearch.ts
- frontend/src/pages/SearchResult/SearchResult.tsx
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.stories.tsx
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.styles.ts
- frontend/src/pages/SearchResult/SearchResultContent/SearchResultContent.tsx
- frontend/src/types.ts
검색 결과 페이지 필터 & 무한스크롤 api 반영했슴다~!
Closes #556
> [FE] refactor: 검색 결과 페이지 필터 & 무한스크롤

- frontend/src/App.tsx
- frontend/src/index.tsx
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
Kakao init 중복 에러 수정
local에선 잘 돌아가는데 왤까요? 이렇게 하면 해결되나?
> [FE] Kakao init 중복 에러 수정

- frontend/webpack.prod.js
> [FE] chore: prod 빌드에 source-map 포함

- backend/src/main/java/com/wooteco/nolto/WebConfig.java
- 쿠키가 저장이 안되요 `withCrendential=true`
- Closes #560
> fix: withCredential 적용

- backend/src/main/java/com/wooteco/nolto/image/application/ImageService.java
- 이미지 리사이징 하는 과정에서 같은 이미지 객체가 중복되어 삭제 되는 경우를 수정합니다.
> fix: 리사이징 이미지 중복 삭제 케이스 수정

- frontend/.husky/pre-push
- frontend/package.json
- frontend/src/components/@common/Markdown/Markdown.styles.ts
- frontend/src/components/@common/Markdown/Markdown.tsx
- frontend/src/components/FeedUploadForm/FeedUploadForm.styles.ts
- frontend/src/components/FeedUploadForm/FeedUploadForm.tsx
- frontend/src/constants/api.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- frontend/yarn.lock
> [FE] refactor: 마크다운 스타일 수정

- frontend/package.json
- frontend/src/components/@common/Markdown/Markdown.styles.ts
- frontend/src/components/@common/Markdown/Markdown.tsx
- frontend/yarn.lock
> [FE] fix: syntax highlighter 제거

- backend/src/main/java/com/wooteco/nolto/image/application/ImageKind.java
- backend/src/main/resources/application.yml
nolto-default-thumbnail.png -> nolto-default-user-profile.png
Closes #571
> refactor: 유저 프로필 기본 이미지 변경

- frontend/src/Global.styles.ts
- frontend/src/components/@common/SOSFlag/SOSFlag.styles.ts
- frontend/src/components/FeedThumbnail/FeedThumbnail.styles.ts
- frontend/src/components/FeedThumbnail/FeedThumbnail.tsx
- frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
- frontend/src/constants/api.ts
- frontend/src/hooks/useTheme.ts
- frontend/themes.ts
- 추석 테마 localStorage 수정, 배경색 다듬기
- 최신 토이 프로젝트 한글화
- 이미지 `object-fit: cover`
- 도움요청 flag에 shadow
- cookie에 withCredential 추가
> [FE] v2.0.0 FE hot fix 

- backend/src/main/java/com/wooteco/nolto/ViewHistoryManager.java
- 쿠키에 same-site none 설정 추가
- ResponseCookie 사용으로 변경
- https://developer.mozilla.org/ko/docs/Web/HTTP/Cookies
- https://dololak.tistory.com/546
> fix(): 쿠키에 same-site none 설정 추가

- backend/src/main/java/com/wooteco/nolto/ViewHistoryManager.java
> fix(): 쿠키에 same-site none 설정 추가 (#578)

- frontend/src/Global.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- 전체 페이지의 height
- 피드 상세 페이지의 기술 스택
> [FE] fix: 스타일 수정

- frontend/src/Global.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
Reverts woowacourse-teams/2021-nolto#580
> Revert "[FE] fix: 스타일 수정"

- backend/src/main/java/com/wooteco/nolto/ViewHistoryManager.java
- frontend/src/Global.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.styles.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- 전체 페이지의 height
- 피드 상세 페이지의 기술 스택
> v2.0.0 핫픽스

- frontend/src/components/@common/Avatar/Avatar.styles.ts
- frontend/src/components/@common/Avatar/Avatar.tsx
- frontend/src/components/FeedThumbnail/FeedThumbnail.tsx
- frontend/src/components/UserProfile/UserProfile.styles.ts
- frontend/src/components/UserProfile/UserProfile.tsx
- frontend/src/pages/Mypage/Intro/Intro.styles.ts
- frontend/src/pages/Mypage/Intro/Intro.tsx
- frontend/src/pages/Upload/Upload.tsx
> fix: user image mp4 대응

- frontend/src/components/FeedThumbnail/FeedThumbnail.tsx
> fix: 구글, 깃헙 기본 프로필 이미지 확장자 대응

- frontend/custom.d.ts
- frontend/global.d.ts
- frontend/tsconfig.json
- declare 파일을 분리하여 svg import 문제 수정
> [FE] fix: declare 파일을 분리하여 svg import 문제 수정

- backend/src/test/java/com/wooteco/nolto/acceptance/AcceptanceTest.java
> fix(): 테스트 전 데이터 베이스 초기화

- backend/src/test/java/com/wooteco/nolto/acceptance/NotificationAcceptanceTest.java
> fix(NotificationAcceptanceTest): 필요없는 기술스택 추가하는 테스트 코드 로직 삭제

- backend/src/main/resources/application.yml
- frontend/package.json
> Relase 4.0.0

- frontend/src/components/CommentModule/@common/Comment/Comment.tsx
- frontend/src/components/Searchbar/Searchbar.tsx
- frontend/src/contexts/member/MemberProvider.tsx
- frontend/src/hooks/queries/comment/useCommentWrite.ts
- frontend/src/hooks/useTheme.ts
- frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
- frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.tsx
- frontend/src/utils/CustomError.ts
- frontend/src/utils/HttpError.ts
> [FE] refactor: 주석 제거
